from typing import Any, Dict, Optional

from troveclient.shell import TroveClientArgumentParser

def load_auth_system_opts(parser: TroveClientArgumentParser): ...
def load_plugin(auth_system: str): ...

class BaseAuthPlugin(object):
    def get_auth_url(self) -> Optional[str]: ...
    @staticmethod
    def add_opts(parser: TroveClientArgumentParser) -> TroveClientArgumentParser: ...
    def parse_opts(self, args: Dict) -> Dict: ...
    def authenticate(self, cls: Any, auth_url: str): ...
